/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "sanctum.csrf-cookie": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [],
    "password.update": [],
    "google.redirect": [],
    "google.callback": [],
    "verification.notice": [],
    "verification.verify": [],
    "verification.send": [],
    "logout": [],
    "sessions.index": [],
    "sessions.logout-others": [],
    "dashboard": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
